function val = EulerAngle2TransferMatrix(ang)
% obtain transfer matrixes from Euler angles
% G ( sample to crystal )
% ang : ( n*3 ) , val : ( 3*(3*n) )
% rad
n = length(ang);
A1 = ang(:,1); B = ang(:,2); A2 = ang(:,3);
val = [ cos(A1).*cos(A2) - sin(A1).*sin(A2).*cos(B) , ...
        sin(A1).*cos(A2) + cos(A1).*sin(A2).*cos(B) , ...
        sin(A2).*sin(B) ; ...
        -cos(A1).*sin(A2) - sin(A1).*cos(A2).*cos(B) , ...
        -sin(A1).*sin(A2) + cos(A1).*cos(A2).*cos(B) , ...
        cos(A2).*sin(B) ; ...
        sin(A1).*sin(B) , ...
        -cos(A1).*sin(B) , ...
        cos(B) ];
val = reshape(val',[3*n,3])';
end