function val = EulerAngle2InvertTransferMatrix(ang)
% obtain transfer matrixes from Euler angles
% inv of G ( crystal to sample )
% ang : ( n*3 ) , val : ( 3n*3 )'
% rad
n = size(ang,1);
A1 = ang(:,3); B = ang(:,2); A2 = ang(:,1);
val = [ cos(A1).*cos(A2) - sin(A1).*sin(A2).*cos(B) , ...
        -sin(A1).*cos(A2) - cos(A1).*sin(A2).*cos(B) , ...
        sin(A2).*sin(B) ; ...
        cos(A1).*sin(A2) + sin(A1).*cos(A2).*cos(B) , ...
        -sin(A1).*sin(A2) + cos(A1).*cos(A2).*cos(B) , ...
        -cos(A2).*sin(B) ; ...
        sin(A1).*sin(B) , ...
        cos(A1).*sin(B) , ...
        cos(B) ];
val = reshape(val',[3*n,3]);
end