function CoordinaterealtionMenuSelected(~,~,app)
if ishandle(app.CoordinaterealtionFig)
    delete(app.CoordinaterealtionFig)
end
pos = app.SchmidtfactorcalculatorUIFigure.Position;
siz = [400,400];
pos(1) = pos(1)+pos(3)/2-siz(1)/2;
pos(2) = pos(2)+pos(4)/2-siz(2)/2;
pos(3:4) = siz;
app.CoordinaterealtionFig = uifigure( ...
    'Position',pos, ...
    'Name','Coordinate Realtion', ...
    'NumberTitle','off', ...
    'ToolBar','none', ...
    'MenuBar','none', ...
    'Resize','off');
gap = [50,50];
axe = uiaxes(app.CoordinaterealtionFig, ...
    'Box','off', ...
    'Color',[1,1,1]', ...
    'Position',[gap,siz(1)-2*gap(1),siz(2)-sum(gap)], ...
    'NextPlot','add');
x = 4; y = 5; z = 3;
Alpha = 0.8;
vert = [0 0 0; x 0 0; x y 0; 0 y 0; 0 0 z; x 0 z; x y z; 0 y z];
fac = [1 2 6 5;
       2 3 7 6;
       3 4 8 7;
       4 1 5 8;
       1 2 3 4;
       5 8 7 6];
Patch = arrayfun(@(i) patch(axe, ...
        'Vertices',vert,'Faces',fac(i,:),...
        'FaceVertexCData',i,'FaceColor','flat', ...
        'ButtonDownFcn',{@PatchButtonDownFcn}, ...
        'FaceAlpha',Alpha, ...
        'UserData',struct('Num',i,'SelectFlag',false)), ...
        1:6);
ratio = 1.2;
dev = 0.2;
line(axe, ...
    [x,x],[y,y-y*ratio],[z,z], ...
    'Color','black', ...
    'LineWidth',2)
text(axe, ...
    x , y-y*ratio-dev , z , ...
    'X', ...
    'Color','black', ...
    'FontSize',20, ...
    'HorizontalAlignment','center')
line(axe, ...
    [x,x-x*ratio],[y,y],[z,z], ...
    'Color','black', ...
    'LineWidth',2)
text(axe, ...
    x-x*ratio-dev , y , z , ...
    'Y', ...
    'Color','black', ...
    'FontSize',20, ...
    'HorizontalAlignment','center')
text(axe, ...
    x+dev , y+dev , z+dev , ...
    'O', ...
    'Color','black', ...
    'FontSize',20, ...
    'HorizontalAlignment','center')

view(axe,3)
axis(axe,'vis3d')
axis(axe,'off')
axis(axe,'equal')

siz2 = [80,35];
ConfirmButton = uibutton(app.CoordinaterealtionFig, ...
    'Text','Confirm', ...
    'Position',[siz(1) - siz2(1)-10,10,siz2], ...
    'ButtonPushedFcn',{@ConfirmButtonPushedFcn});
RotateButton = uibutton(app.CoordinaterealtionFig, ...
    'Text','Rotate', ...
    'Position',[ConfirmButton.Position(1) - siz2(1)-10,10,siz2], ...
    'ButtonPushedFcn',{@RotateButtonPushedFcn});

Text = uilabel(app.CoordinaterealtionFig, ...
        'Text','',...
        'Position',[30,30,100,100], ...
        'FontName','Times New Roman', ...
        'FontSize',18, ...
        'HorizontalAlignment','left');
    
x_line = []; x_text = [];
y_line = []; y_text = [];
o_text =[];
StartInd = 1;
G = [];
function PatchButtonDownFcn(face,~)
    for i =1:6
        Patch(i).UserData.SelectFlag = false;
        Patch(i).FaceAlpha = Alpha;
        Patch(i).EdgeColor = [0 0 0];
        Patch(i).LineWidth = 0.5;
    end
    face.LineWidth = 1;
    face.FaceAlpha = 1;
    face.UserData.SelectFlag = true;
    
    Vertices = face.Vertices(face.Faces,:);
    delete(x_line); delete(x_text);
    x_line = line(axe, ...
        Vertices(1:2,1),Vertices(1:2,2),Vertices(1:2,3), ...
        'Color','red', ...
        'LineWidth',2);
    x_text = text(axe, ...
        Vertices(2,1),Vertices(2,2),Vertices(2,3), ...
        'x', ...
        'Color','red', ...
        'FontSize',20, ...
        'HorizontalAlignment','center');
    delete(y_line); delete(y_text);
    y_line = line(axe, ...
        Vertices([1,4],1),Vertices([1,4],2),Vertices([1,4],3), ...
        'Color','red', ...
        'LineWidth',2);
    y_text = text(axe, ...
        Vertices(4,1),Vertices(4,2),Vertices(4,3), ...
        'y', ...
        'Color','red', ...
        'FontSize',20, ...
        'HorizontalAlignment','center');
    delete(o_text);
    o_text = text(axe, ...
        Vertices(1,1),Vertices(1,2),Vertices(1,3), ...
        'o', ...
        'Color','red', ...
        'FontSize',20, ...
        'HorizontalAlignment','center');
    X = diff(Vertices(1:2,:)); X = X./norm(X);
    Y = diff(Vertices([1,4],:)); Y = Y./norm(Y);
    Z = cross(X,Y);
    G = [X',Y',Z']; % coord2 -> smaple coord
    Text.Text = {num2str(G(1,:)),num2str(G(2,:)),num2str(G(3,:))};
    StartInd = 1;
end

function RotateButtonPushedFcn(~,~)
    FaceInd = find(arrayfun(@(face)face.UserData.SelectFlag,Patch),1);
    if isempty(FaceInd) ; return ; end
    face = Patch(FaceInd);
    Vertices = face.Vertices(face.Faces,:);
    delete([x_line,x_text,y_line,y_text,o_text])
    StartInd = rem(StartInd+1,4);
    ind_x = mod([StartInd+4,StartInd+5],4); ind_x(ind_x==0)=4;
    x_line = line(axe, ...
        Vertices(ind_x,1),Vertices(ind_x,2),Vertices(ind_x,3), ...
        'Color','red', ...
        'LineWidth',2);
    x_text = text(axe, ...
        Vertices(ind_x(2),1),Vertices(ind_x(2),2),Vertices(ind_x(2),3), ...
        'x', ...
        'Color','red', ...
        'FontSize',20, ...
        'HorizontalAlignment','center');
    ind_y = mod([StartInd+4,StartInd+3],4); ind_y(ind_y==0)=4;
    y_line = line(axe, ...
        Vertices(ind_y,1),Vertices(ind_y,2),Vertices(ind_y,3), ...
        'Color','red', ...
        'LineWidth',2);
    y_text = text(axe, ...
        Vertices(ind_y(2),1),Vertices(ind_y(2),2),Vertices(ind_y(2),3), ...
        'y', ...
        'Color','red', ...
        'FontSize',20, ...
        'HorizontalAlignment','center');
    o_text = text(axe, ...
        Vertices(ind_y(1),1),Vertices(ind_y(1),2),Vertices(ind_y(1),3), ...
        'o', ...
        'Color','red', ...
        'FontSize',20, ...
        'HorizontalAlignment','center');
    X = diff(Vertices(ind_x,:)); X = X./norm(X);
    Y = diff(Vertices(ind_y,:)); Y = Y./norm(Y);
    Z = cross(X,Y);
    G = [X',Y',Z']; % coord2 -> smaple coord
    Text.Text = {num2str(G(1,:)),num2str(G(2,:)),num2str(G(3,:))};
end

function ConfirmButtonPushedFcn(~,~)
    FaceInd = find(arrayfun(@(face)face.UserData.SelectFlag,Patch),1);
    if isempty(FaceInd) ; return ; end
    face = Patch(FaceInd);
    Vertices = face.Vertices(face.Faces,:);
    ind_x = mod([StartInd+4,StartInd+5],4); ind_x(ind_x==0)=4;
    ind_y = mod([StartInd+4,StartInd+3],4); ind_y(ind_y==0)=4;
    X = diff(Vertices(ind_x,:)); X = X./norm(X);
    Y = diff(Vertices(ind_y,:)); Y = Y./norm(Y);
    Z = cross(X,Y);
    app.CoordinaterealtionMatrix = [X',Y',Z']; % coord2 -> smaple coord
    delete(app.CoordinaterealtionFig)
end

end