function IPFscatterMenuSelected(menu,~,app)
if strcmp(menu.Checked, 'off')
    menu.Checked = 'on';
    app.IPFscatFlag = 1;
    app.FreezeButton.Enable = 'on';
    pos = app.SchmidtfactorcalculatorUIFigure.Position;
    pos(1) = pos(1) + pos(3)+20;
    pos(2) = pos(2);
    pos(3:4) = [450,450];
    app.IPFscatFig = figure( ...
        'Position',pos, ...
        'Name','IPF', ...
        'NumberTitle','off', ...
        'Resize','off', ...
        'CloseRequestFcn',{@IPFscatCloseRequestFcn,app});
%     'ToolBar','none', ...
%         'MenuBar','none', ...
    app.IPFscatFig.UserData.SurfNum = 0;
    app.IPFscatFig.UserData.DirNum = 0;
    app.IPFscatFig.UserData.VecData = [];
    app.IPFscatFig.UserData.VecSampleData = [];
    
    wid = 15;
    wid2 = 80;
    wid3 = 0;
    app.IPFscatAxe = polaraxes(app.IPFscatFig, ...
        'Box','off', ...
        'Color',[1,1,1], ...
        'Unit','pixels', ...
        'RLim',[0,1]);
    box on
    app.IPFscatAxe.Position = ...
        [wid,wid+wid2+wid3+30,450-2*wid,450-2*wid-wid2-wid3-70];
    app.IPFscatAxe.RAxis.Visible = 'off';
    app.IPFscatAxe.ThetaAxis.Visible = 'off';
    app.IPFscatAxe.RGrid = 'off';
    app.IPFscatAxe.ThetaGrid = 'off';
    hold(app.IPFscatAxe,'on');
    app.IPFscatUic.Panel(1) = uipanel(app.IPFscatFig,'Units','pixels');
    panelsiz1 = [100,80];
    pos1 = 130;
    app.IPFscatUic.Panel(1).Position = [wid+pos1,wid+wid3,panelsiz1];
    app.IPFscatUic.Panel(2) = uipanel(app.IPFscatFig,'Units','pixels');
    panelsiz2 = [125,80];
    app.IPFscatUic.Panel(2).Position = [wid+pos1+panelsiz1(1),wid+wid3,panelsiz2];
    panelsiz3 = [70,80];
    app.IPFscatUic.Panel(3) = uipanel(app.IPFscatFig,'Units','pixels');
    app.IPFscatUic.Panel(3).Position = [wid+pos1+panelsiz1(1)+panelsiz2(1),wid+wid3,panelsiz3];
    CheckBoxString = {'pole','trace','direction'};
    for i = 1:3
        app.IPFscatUic.Edit(i) = uicontrol(app.IPFscatUic.Panel(2), ...
            'Style','edit', ...
            'String','', ...
            'Position',[5+30*(i-1),45,25,25]);
        app.IPFscatUic.Edit(i+3) = uicontrol(app.IPFscatUic.Panel(2), ...
            'Style','edit', ...
            'String','', ...
            'Position',[5+30*(i-1),10,25,25]);
        app.IPFscatUic.Checkboxes(i) = uicontrol(app.IPFscatUic.Panel(3), ...
            'Style','checkbox', ...
            'String',CheckBoxString{i}, ...
            'Position',[5,5+25*(i-1),65,20], ...
            'Value',1);
    end
    app.IPFscatUic.Button(1) = uicontrol(app.IPFscatUic.Panel(2), ...
        'Style','pushbutton', ...
        'String','Add', ...
        'Position',[95,45,25,25], ...
        'CallBack',{@IPFscatAddSurfDirButtonCallback,app});
    app.IPFscatUic.Button(2) = uicontrol(app.IPFscatUic.Panel(2), ...
        'Style','pushbutton', ...
        'String','Add', ...
        'Position',[95,10,25,25], ...
        'CallBack',{@IPFscatAddDirButtonCallback,app});
    app.IPFscatUic.ListBox = uicontrol(app.IPFscatUic.Panel(1), ...
        'Style','listbox', ...
        'String',{}, ...
        'Position',[5,5,60,70], ...
        'Callback',{@IPFscatListBoxCallback,app});
    app.IPFscatUic.Button(3) = uicontrol(app.IPFscatUic.Panel(1), ...
        'Style','pushbutton', ...
        'String','Del', ...
        'Position',[70,10,25,25], ...
        'CallBack',{@IPFscatDelButtonCallback,app});
    app.IPFscatUic.Button(4) = uicontrol(app.IPFscatUic.Panel(1), ...
        'Style','pushbutton', ...
        'String','Imp', ...
        'Position',[70,45,25,25], ...
        'CallBack',{@IPFscatImpButtonCallback,app});
    app.IPFscatUic.Text = uicontrol(app.IPFscatFig, ...
        'Style','text', ...
        'String','',...
        'Position',[15,15,130,90], ...
        'FontName','Times New Roman', ...
        'FontSize',12, ...
        'HorizontalAlignment','left');
else
    menu.Checked = 'off';
    delete(app.IPFscatFig);
    app.IPFscatFlag = 0;
end