function PFscatterMenuSelected(menu,~,app)
if strcmp(menu.Checked, 'off')
    menu.Checked = 'on';
    app.PFscatFlag = 1;
    app.FreezeButton.Enable = 'on';
    pos = app.SchmidtfactorcalculatorUIFigure.Position;
    pos(1) = pos(1) + pos(3)+20;
    pos(2) = pos(2);
    pos(3:4) = [450,450];
    app.PFscatFig = figure( ...
        'Position',pos, ...
        'Name','PF', ...
        'NumberTitle','off');
    wid = 15;
    wid2 = 80;
    wid3 = 0;
    app.PFscatAxe = polaraxes(app.PFscatFig, ...
        'Box','off', ...
        'Color',[1,1,1], ...
        'Unit','pixels');
    box on
    app.PFscatAxe.Position = ...
        [wid,wid+wid2+wid3+30,450-2*wid,450-2*wid-wid2-wid3-70];
    app.PFscatAxe.RAxis.Visible = 'off';
    app.PFscatAxe.ThetaAxis.Visible = 'off';
    app.PFscatAxe.RGrid = 'off';
    app.PFscatAxe.ThetaGrid = 'off';
    hold(app.PFscatAxe,'on');
    app.PFscatFig.CloseRequestFcn = {@PFscatCloseRequestFcn,app};
    
    app.PFscatUic.Panel(1) = uipanel(app.PFscatFig,'Units','pixels');
    panelsiz1 = [120,80];
    app.PFscatUic.Panel(1).Position = [wid+180,wid+wid3,panelsiz1];
    app.PFscatUic.Panel(2) = uipanel(app.PFscatFig,'Units','pixels');
    panelsiz2 = [126,80];
    app.PFscatUic.Panel(2).Position = [wid+180+panelsiz1(1),wid+wid3,panelsiz2];
    
    app.PFscatUic.Checkboxes(1) = uicontrol(app.PFscatUic.Panel(1), ...
        'Style','checkbox', ...
        'String','orientation', ...
        'Position',[10,55,100,20], ...
        'Value',app.PFscatOpt(1), ...
        'UserData',1, ...
        'CallBack',{@PFscatCheckboxCallback,app});
    app.PFscatUic.Checkboxes(2) = uicontrol(app.PFscatUic.Panel(1), ...
        'Style','checkbox', ...
        'String','surafce trace', ...
        'Position',[10,30,100,20], ...
        'Value',app.PFscatOpt(2), ...
        'UserData',2, ...
        'CallBack',{@PFscatCheckboxCallback,app});
    app.PFscatUic.Checkboxes(3) = uicontrol(app.PFscatUic.Panel(1), ...
        'Style','checkbox', ...
        'String','surafce pole', ...
        'Position',[10,5,100,20], ...
        'Value',app.PFscatOpt(3), ...
        'UserData',3, ...
        'CallBack',{@PFscatCheckboxCallback,app});
    [app.PFscatUic.Checkboxes.FontSize] = deal(10);
    editsiz = [18,20];
    for j = 1:3
        for i = 1:4
           app.PFscatUic.Edit(j,i) = uicontrol(app.PFscatUic.Panel(2), ...
               'Style','edit', ...
               'Position',[(i-1)*26+15,80-25*j,editsiz], ...
               'String',num2str(app.PFscatInd(j,i)), ...
               'Callback',{@PFscatIndEditCallback,app}, ...
               'UserData',[i,j]);
           if i == 3
               app.PFscatUic.Edit(j,i).Enable = 'off';
           end
        end
    end
    app.PFscatUic.NamCheckbox = uicontrol(app.PFscatFig, ...
        'Style','checkbox', ...
        'String','Show Index', ...
        'Position',[wid+180-100,wid+wid3,100,30], ...
        'FontSize',10, ...
        'Value',app.PFscatOpt(4), ...
        'UserData',4, ...
        'CallBack',{@PFscatCheckboxCallback,app});
    theta = 0:0.01:2*pi;
    r = ones(1,length(theta));
    polarplot(app.PFscatAxe,theta,r,'LineWidth',1,'Color','black');
    app.PFscatAxe.RLim = [0,1];
    app.PFscatUic.Text = uicontrol(app.PFscatFig, ...
        'Style','text', ...
        'Position',[wid,wid+wid3+30,150,50], ...
        'FontName','Times New Roman', ...
        'FontSize',12, ...
        'HorizontalAlignment','left');
else
    menu.Checked = 'off';
    delete(app.PFscatFig);
    app.PFscatFlag = 0;
end